- observer.py
- pyth_observer/prices.py
Given a publishers.json such as the following:
{
"mainnet": {
"pubkey123": "degen_publisher",
"pubkey234": "boredape"
},
"testnet": {
"pubkey456": "degen_publisher",
"pubkey789": "boredape"
}
}
Properly map the names to more hooman friendly equivalents.
> Fix publisher mapping

- pyth_observer/events.py
Add confidence intervals to alert text so that it's easier to track down issues related to wide spreads on exchanges.
> Improve alert text

- pyth_observer/calendar.py
- pyth_observer/events.py
- program crashes when aggregate price is 0 as it tries to divide delta (publisher aggregate price - aggregate price) by aggregate price
- not sure what's the best way to handle this case but what I did here was to return False if aggregate price is 0 (happy to get suggestions if there are better alternatives)
> fix zero division error in PriceDeviation when aggregate price is 0

- pyth_observer/calendar.py
- pyth_observer/events.py
- pyth_observer/prices.py
- tests/test_price_offline.py
- tests/test_publisher_price_offline.py
https://app.clickup.com/t/1zhfeqy
currently, the program checks if the price account is publishing (status == TRADING, conf interval != 0, slot_diff < 25) before running the individual checks in each events, however this prevents the alert from firing for individual publisher price feed if they went offline (status = UNKNOWN or slot_diff < 25) as the checks don't get run
hence, moving the checks into individual events
appreciate any tips for better alternatives if there are any
> add publisher price feed offline alert

- observer.py
- pyth_observer/events.py
- pyth_observer/prices.py
I messed around with the existing alerts and configuration, and it seems like many of our price feeds flash offline for short periods then come back online. Obviously that situation isn't great and we should fix it. However, it also means that the straightforward price feed down alert is noisy and largely useless.
This PR adds another feed offline check that only alerts if the feed has been down for 600 slots. The check isn't perfect (see code comment), but I think it's worthwhile to have in the short run.
I also marked the PriceFeedOffline alert as noisy. Once we fix the flaky price feeds we can start using PriceFeedOffline.
> Less noisy feed offline alert

- pyth_observer/events.py
Our offline price feed alert fires for the "coming soon" feeds in mainnet with min_publishers >= 10. We expect these feeds to be offline, so turn off the alert in that case. Validated this fix works by running in the console.
> Turn off noisy alert for symbols that are coming soon

- pyth_observer/crosschain.py
Pyth observer is currently down because the newly deployed price service has changed the schema of its returned price feeds. This PR uses the new schema ([link](https://github.com/pyth-network/pyth-sdk-js/blob/main/src/schemas/price_feed.json)). An example output is:
```json
[{"ema_price":{"conf":"385612290","expo":-8,"price":"2008445240000","publish_time":1665079368},"id":"e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43","price":{"conf":"365827995","expo":-8,"price":"2008064619250","publish_time":1665079368}}]
```
The prev_publish_price is not used anywhere. I double checked by reading the usage on `events.py` and searching for `prev_publish_price` on the codebase (as it's a dictionary any usage explicitly use it)
> Fix the cross chain api change problem

- pyproject.toml
- pyth_observer/__init__.py
- pyth_observer/calendar.py
- pyth_observer/check/price_feed.py
- pyth_observer/check/publisher.py
- pyth_observer/event.py
- sample.config.yaml
- tests/test_checks_price_feed.py
This PR mostly fixes some logic bugs or improve them. Also updates the calendar for the new year.
Please see my comments for further explanation.
> Bug fix + improvement

- pyproject.toml
- pyth_observer/calendar.py
- pyth_observer/check/publisher.py
- Update market hours to support FX/Metal properly
- Improve PublisherPriceCheck log
- Bump version to 0.1.3
> Improvements_again

- pyproject.toml
- pyth_observer/__init__.py
Fix a bug where aggregate confidence interval is set to be the component confidence interval instead
> Fix aggregate confidence interval

- pyproject.toml
- pyth_observer/event.py
This PR includes publisher key in the aggregate key of a PublisherCheck. It allows us to mute specific publisher instead of muting all the entire check from datadog (which is not good)
> Improve datadog aggregate key for publisher checks

- pyproject.toml
- pyth_observer/__init__.py
- pyth_observer/check/price_feed.py
There are some feeds on mainnet that are not available on pythnet and hence not available on price service. This is causing the mainnet observer to crash. This code makes the crosschain price optional as fix. This will also handle the scenario that a price on Pythnet does not reach the price server properly.
> Make crosschain price optional

- pyproject.toml
- pyth_observer/check/publisher.py
- tests/test_checks_price_feed.py
- tests/test_checks_publisher.py
the check now compares against the closer side of the publisher's confidence interval instead of the publisher's price.
> Account for confidence interval in price difference check

- Dockerfile
- pyth_observer/check/price_feed.py
- pyth_observer/crosschain.py
- tests/test_checks_price_feed.py
This fixes a bug where crosschain prices are considered stale because a long time passes between fetching the prices from the price service and checking the staleness. 
This bug also exists on the current pythnet deployment. I think the reason it went undetected is that the main loop is faster on pythnet because the rpc node is faster.
> Fix crosschain staleness check

- pyproject.toml
- pyth_observer/crosschain.py
- sample.config.yaml
The HTTP library in hermes expects array parameters passed in URLs to be encoded with `ids[]=`, but the aiohttp library used here does not support encoding this way. This PR updates the call to hand-serialize the URL parameters to match hermes expectations.
> fix: manual encode array params for hermes

- pyproject.toml
- pyth_observer/check/price_feed.py
- pyth_observer/check/publisher.py
- pyth_observer/event.py
this now creates logs with the following format:
```
{
"text": "2024-05-09 17:06:54.951 | INFO     | pyth_observer.event:send:97 - dv (5ZLaVaVJdvdqGmvnS4jYgJ7k54Kdev7f1q5LDytjwqJ6) price is too far from aggregate price.\n",
"record": {
"elapsed": { "repr": "0:01:02.179121", "seconds": 62.179121 },
"exception": null,
"extra": {
"msg": "dv (5ZLaVaVJdvdqGmvnS4jYgJ7k54Kdev7f1q5LDytjwqJ6) price is too far from aggregate price.",
"type": "PublisherCheck",
"publisher": "dv (5ZLaVaVJdvdqGmvnS4jYgJ7k54Kdev7f1q5LDytjwqJ6)",
"symbol": "Crypto.ENJ/USD",
"publisher_price": "0.31184499 ± 0.00585499",
"aggregate_price": "0.29085248 ± 0.00217723",
"deviation": 5.204535302569867
},
"file": {
"name": "event.py",
"path": "/Users/ayazabbas/dev/pyth/pyth-observer/pyth_observer/event.py"
},
"function": "send", …
```
> format log events in json

- Makefile
- README.md
- pyproject.toml
- pyth_observer/dispatch.py
- pyth_observer/event.py
- pyth_observer/zenduty.py
Adds a Zenduty Event type, which requires us to manually resolve an incident once it surpasses so I have added logic to monitor open alerts and resolve them if the last alert was > 2 minutes ago. Open alerts are written to a file for persistence across app restarts, so we don't end up with orphaned unresolved incidents.
> Add zenduty integration

- pyproject.toml
- pyth_observer/dispatch.py
- pyth_observer/zenduty.py
Tested locally and works as expected. Should greatly reduce noise by only alerting if a check fails 3 times without self-resolving within 2 minutes.
> reduce noise of zenduty alerts

- pyproject.toml
- pyth_observer/__init__.py
- pyth_observer/check/publisher.py
- sample.config.yaml
- tests/test_checks_publisher.py
we agree that `PublisherStalledCheck` should fulfil these 3 requirements:
- should be skipped when market hours is closed
- should be skipped when publisher is offline (`PublisherOfflineCheck` fails)
- should be skipped when `PublisherOfflineCheck` returns true but `distance > self.__abandoned_slot_distance`
there seems to be 2 ways we can do this:
- duplicating the offline check logic in `PublisherStalledCheck` including modifying the check to accept `max_slot_distance` and `abandoned_slot_distance` fields which don't really seem to belong there since this is for `PublisherOfflineCheck`
- make sure `PublisherStalledCheck` runs after `PublisherOfflineCheck` and keep track of the deps with flags
instead of modifying `PublisherStalledCheck` to also accept `max_slot_distance` and …
> fix: skip PublisherStalledCheck if PublisherOfflineCheck fails

- README.md
- pyproject.toml
- pyth_observer/dispatch.py
- sample.config.yaml
Some checks are noisier than others, this change allows us to set alert and resolution thresholds per check type.
> set customisable thresholds for zenduty alerts

- README.md
- pyproject.toml
- pyth_observer/dispatch.py
- sample.config.yaml
This change puts telegram events under the same threshold rules as zenduty events.
> telegram event noise reduction

- pyproject.toml
- pyth_observer/__init__.py
If a feed's min_publishers count is 255, it's not live yet (coming soon.) These feeds should be excluded from alerts.
> Exclude coming soon feeds from alerts

- pyproject.toml
- pyth_observer/zenduty.py
API Integration is being [deprecated](https://zenduty.com/docs/api-integration/).
[IMPORTANT] We're phasing out the API-
> ⚠️ **[Integration]** We're phasing out the API-Integration in favour of the [Generic Integration](https://zenduty.com/docs/generic-integration/). Starting **October 15th, 2024**, no new API-Integration integrations can be created. We will continue to support the existing API-Integrations until **March 31st, 2025**, after which they will stop working. We recommend you to migrate the existing API-Integrations to the [Generic Integration](https://zenduty.com/docs/generic-integration/) at your earliest convenience.
> update zenduty endpoint

- pyth_observer/__init__.py
- pyth_observer/dispatch.py
- pyth_observer/metrics.py
> feat(reliability) Add metrics

- pyth_observer/__init__.py
- pyth_observer/cli.py
- pyth_observer/dispatch.py
- pyth_observer/metrics.py
We want to run multiple redundant instances of `pyth-observer` which poses an interesting problem around coordinations and alert deduplication. With `ZenDuty` we get deduplication for free - we just send it a hash and it does the rest for us - but `Telegram` does not offer the same functionality. 
Longer term we might need to run istio coordination layer (or just use some db 🤷 ) but for now we can at least get reliable zenduty alerts even if tg isn't there yet.
> feat(reliability) Add flag to disable `telegram` notifications

- pyth_observer/__init__.py
- pyth_observer/cli.py
- pyth_observer/dispatch.py
- pyth_observer/metrics.py
Reverts pyth-network/pyth-observer#92
> Revert "feat(reliability) Add flag to disable `telegram` notifications"
